# Generated by Django 5.1.4 on 2026-06-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studresourceapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resources/'),
        ),
        migrations.AddField(
            model_name='resource',
            name='subject',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
